import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"
import TopHeader from "./component/header/top_header";
import Navbar from "./component/header/navbar";
import Footer from "./component/footer";
const poppins_init = Poppins({
  weight: ['400', '500', '600', '700'], // Choose your weights
  subsets: ['latin'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins_init.variable}>
        <TopHeader/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
